import { header, footer } from './components.js';
import { site, whatsappUrl } from './data/site.js';
import { currencies } from './data/pricing.js';
import { escapeHtml as e } from './modules/safety.js';

const stages = ['You', 'The work', 'Your business', 'Investment', 'Timing', 'The idea', 'Contact', 'Review'];
const services = ['Website', 'Premium interactive website', 'E-commerce', 'AI product / MVP', 'Automation', 'Brand / visual', 'Video / motion', 'Ongoing growth', 'Not sure yet'];
const budgets = [
  { value: 'below-15k', label: 'Below ₹15k', max: 15000 },
  { value: '15k-30k', label: '₹15k–₹30k', min: 15000, max: 30000 },
  { value: '30k-60k', label: '₹30k–₹60k', min: 30000, max: 60000 },
  { value: '60k-1l', label: '₹60k–₹1L', min: 60000, max: 100000 },
  { value: '1l-2.5l', label: '₹1L–₹2.5L', min: 100000, max: 250000 },
  { value: '2.5l-plus', label: '₹2.5L+', min: 250000 },
  { value: 'discuss', label: 'Not sure yet' },
];
const arrow = '<span aria-hidden="true">↗</span>';
const input = (label, name, options = '') => `<label class="flow-field">${label}<input name="${name}" ${options}></label>`;
function step(index, title, intro, content) {
  return `<section class="flow-step" data-flow-step="${index}" aria-labelledby="flow-title-${index}"><p class="flow-kicker">${String(index + 1).padStart(2, '0')} / ${e(stages[index])}</p><h2 id="flow-title-${index}" tabindex="-1">${title}</h2><p class="flow-explainer">${intro}</p>${content}<p class="flow-step-error" role="alert" data-step-error></p></section>`;
}
function choice(name, value, label, type = 'radio', extra = '') {
  return `<label class="flow-choice"><input type="${type}" name="${name}" value="${e(value)}" ${extra}><span>${e(label)}</span><i aria-hidden="true">${type === 'checkbox' ? '+' : '↗'}</i></label>`;
}

export function startProject() {
  return `${header()}<main id="main" class="project-flow" data-project-flow><div id="top"></div><div class="flow-layout"><aside class="flow-intro"><a class="flow-back" href="/#work">← Back to selected work</a><p class="flow-kicker">KIRATVEER SINGH RALHAN / PROJECT ENQUIRY</p><h1>Good work starts<br>with a conversation.</h1><p>A rough idea is enough. Let’s find out what it could become.</p><div class="flow-identity" aria-hidden="true"><span>K</span><span>R</span></div><div class="flow-direct"><span>PREFER TO TALK?</span><a href="${whatsappUrl}" target="_blank" rel="noopener noreferrer" data-track="cta:whatsapp">WhatsApp ${arrow}</a><a href="mailto:${site.email}" data-track="cta:email">Email Kirat ${arrow}</a></div></aside><div class="flow-workspace"><div class="flow-progress-top"><span>THE PROJECT BRIEF</span><span data-flow-count aria-live="polite">01 / 08</span></div><nav class="flow-progress" aria-label="Project brief steps">${stages.map((stage, index) => `<button type="button" data-flow-jump="${index}" aria-label="Step ${index + 1}: ${stage}" ${index === 0 ? 'aria-current="step"' : 'disabled'}><span>${String(index + 1).padStart(2, '0')}</span><span>${stage}</span></button>`).join('')}</nav><form id="project-enquiry" action="${site.formEndpoint}" method="POST" autocomplete="on"><input type="hidden" name="_subject" value="New project enquiry — Kirat"><input type="hidden" name="billing_currency" value="INR"><div class="honeypot" aria-hidden="true"><label>Leave this empty<input name="_gotcha" tabindex="-1" autocomplete="off"></label></div>
  ${step(0, 'What should I<br>call you?', 'First, a little about the person behind the idea.', `<div class="flow-fields">${input('Your name', 'name', 'required autocomplete="name" maxlength="150" placeholder="Your name"')}${input('Company / brand <small>Optional</small>', 'business', 'autocomplete="organization" maxlength="200" placeholder="The name behind the work"')}${input('Location / timezone <small>Optional</small>', 'location', 'maxlength="150" placeholder="e.g. London / GMT"')}</div>`)}
  ${step(1, 'What are<br>we building?', 'Choose the areas you have in mind. A combination is welcome.', `<fieldset class="flow-options flow-services"><legend class="flow-sr-only">Select one or more services</legend>${services.map(service => choice('services', service, service, 'checkbox')).join('')}</fieldset>`)}
  ${step(2, 'Where are<br>you now?', 'An existing business, a new product, or something still taking shape.', `<div class="flow-fields">${input('Current website <small>Optional</small>', 'website', 'type="url" inputmode="url" maxlength="2000" placeholder="https://"')}<label class="flow-field">A little about your business / product<textarea name="business_context" rows="4" maxlength="3000" placeholder="Who is it for? What do you do? A few sentences are enough."></textarea></label></div>`)}
  ${step(3, 'What investment<br>feels right?', 'This gives the conversation a useful starting point. It is not a final quote.', `<label class="flow-currency">VIEW RANGES IN<select id="currency-select" disabled>${currencies.map(currency => `<option value="${currency.code}">${currency.code} — ${e(currency.symbol)}</option>`).join('')}</select></label><fieldset class="flow-options flow-budgets"><legend class="flow-sr-only">Approximate investment</legend>${budgets.map(budget => choice('budget', budget.value, budget.label, 'radio', `required data-inr-label="${e(budget.label)}" ${budget.min !== undefined ? `data-min="${budget.min}"` : ''} ${budget.max !== undefined ? `data-max="${budget.max}"` : ''}`)).join('')}</fieldset><p class="flow-currency-note" id="currency-note">INR is the base pricing reference. International ranges are approximate and include a cross-border service and currency buffer.</p>`)}
  ${step(4, 'When should<br>this happen?', 'A preferred timeline helps shape a realistic scope.', `<fieldset class="flow-options"><legend class="flow-sr-only">Preferred timeline</legend>${['ASAP', '2–4 weeks', '1–2 months', '2–4 months', 'Flexible'].map(timeline => choice('timeline', timeline, timeline, 'radio', 'required')).join('')}</fieldset><p class="flow-small-note">We will agree availability and delivery dates after reviewing the brief.</p>`)}
  ${step(5, 'What are you trying<br>to make happen?', 'Tell me about the change you want to see. Plain language is perfect.', `<div class="flow-fields"><label class="flow-field">The idea / desired outcome<textarea name="message" rows="5" required minlength="10" maxlength="6000" placeholder="What should this project help your business do?"></textarea></label><label class="flow-field">Reference websites <small>Optional</small><textarea name="references" rows="2" maxlength="2000" placeholder="Links you like, and what you like about them."></textarea></label></div>`)}
  ${step(6, 'Where can<br>I reach you?', 'I will use these details to respond to this enquiry.', `<div class="flow-fields flow-contact-fields">${input('Email', 'email', 'type="email" autocomplete="email" required maxlength="254" placeholder="you@yourbusiness.com"')}${input('WhatsApp / phone <small>Optional for email replies</small>', 'phone', 'type="tel" autocomplete="tel" maxlength="50" placeholder="Country code + number"')}<fieldset class="flow-options flow-methods"><legend>Preferred reply</legend>${choice('preferred_contact', 'email', 'Email', 'radio', 'checked')}${choice('preferred_contact', 'whatsapp', 'WhatsApp', 'radio')}</fieldset><details class="flow-call"><summary>Add a preferred call time <small>Optional</small><span aria-hidden="true">+</span></summary><div>${input('Preferred date / time', 'preferred_call_time', 'type="datetime-local"')}${input('Timezone for the call', 'call_timezone', 'maxlength="100" placeholder="e.g. Asia/Kolkata or UTC +5:30"')}<p>A preference, not a reserved appointment. I will confirm a time with you.</p></div></details></div>`)}
  ${step(7, 'Looks like<br>a good beginning.', 'Take a moment to check the details. You can edit any part before sending.', `<div class="flow-review" data-flow-review></div><p class="flow-submit-note">By sending this brief, you agree that Kirat can use these details to respond to your project enquiry. No newsletter signup.</p>`)}
  <div class="flow-controls"><button class="flow-previous" type="button" data-flow-prev>← Previous</button><button class="flow-next" type="button" data-flow-next>Continue <span aria-hidden="true">→</span></button><button class="flow-next flow-submit" type="submit">Send project brief ${arrow}</button></div><p id="flow-status" class="flow-status" role="status" tabindex="-1" aria-live="polite"></p><noscript><p class="flow-noscript">JavaScript is unavailable, so the full brief is shown below its step headings. Submit to the existing form provider, or contact me through WhatsApp or email.</p></noscript></form><p class="flow-bottom-note">A conversation first. A clear scope next.</p></div></div></main>${footer()}`;
}

export function thankYou() {
  return `${header()}<main id="main" class="flow-confirmation" data-project-flow><div id="top"></div><div class="confirmation-emblem" aria-hidden="true"><svg viewBox="0 0 100 100" fill="none"><circle cx="50" cy="50" r="46"></circle><path d="m30 51 13 13 28-30"></path></svg><span>KR / NEXT CHAPTER</span></div><p class="flow-kicker" data-confirmation-kicker>GOOD THINGS START WITH A CONVERSATION</p><h1 data-confirmation-title>The next<br>chapter.</h1><p class="confirmation-message" data-confirmation-message>A considered brief is the first step toward a considered project. Start a project enquiry or continue the conversation directly.</p><a class="confirmation-start" data-confirmation-start href="/start-project/">Start a project ${arrow}</a><section class="confirmation-next" aria-labelledby="confirmation-next-heading"><h2 id="confirmation-next-heading">What happens after an enquiry</h2><ol><li><span>01</span><div><h3>I read the brief.</h3><p>The idea, the business and what the work needs to achieve.</p></div></li><li><span>02</span><div><h3>We find the direction.</h3><p>I reply with questions or a useful starting point.</p></div></li><li><span>03</span><div><h3>We agree the next move.</h3><p>If we are aligned, we shape the scope, timeline and proposal.</p></div></li></ol></section><div class="confirmation-actions"><a href="${whatsappUrl}" target="_blank" rel="noopener noreferrer" data-track="cta:whatsapp">WhatsApp me ${arrow}</a><a href="/#work">Return to selected work ${arrow}</a>${site.socials.map(social => `<a href="${e(social.url)}" target="_blank" rel="noopener noreferrer">${e(social.name)} ${arrow}</a>`).join('')}</div></main>${footer()}`;
}
