import { site, whatsappUrl, capabilities, process } from './data/site.js';
import { projects, motionWorks } from './data/projects.js';
import { packages, addons, currencies, formatPrice } from './data/pricing.js';
import { escapeHtml as e, safeUrl, safeMedia } from './modules/safety.js';

const arrow='<span aria-hidden="true">↗</span>',startUrl='/start-project/';
const image=(src,alt,cls='',eager=false)=>`<img class="${cls}" src="${e(src)}" alt="${e(alt)}" width="1536" height="1024" loading="${eager?'eager':'lazy'}" decoding="async">`;
const label=(n,text)=>`<p class="scene-label"><span>${n}</span>${text}</p>`;

export function header(){const links=site.navigation.map(l=>`<a href="${l.href}">${e(l.name)}</a>`).join('');return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><a class="brand-mark" href="/" aria-label="Kiratveer Singh Ralhan home"><b>KR</b><span>KIRATVEER<br>SINGH RALHAN</span></a><nav class="desktop-nav" aria-label="Primary">${links}</nav><div class="nav-actions"><button class="theme-toggle" data-theme-toggle type="button" aria-label="Switch to day mode" aria-pressed="false"><i aria-hidden="true"></i><span data-theme-label>NIGHT</span></button><button class="sound-toggle" type="button" aria-pressed="false"><span>SOUND</span> OFF</button><a class="header-cta" href="${startUrl}" data-cursor="START" data-track="cta:start">Start a project ${arrow}</a><button class="menu-toggle" aria-controls="mobile-menu" aria-expanded="false">Menu <span aria-hidden="true">+</span></button></div><div class="reading-progress" aria-hidden="true"></div></header><dialog id="mobile-menu" class="mobile-menu"><div class="menu-top"><a href="/" class="brand-mark"><b>KR</b><span>KIRATVEER<br>SINGH RALHAN</span></a><button class="menu-close" aria-label="Close navigation">Close ×</button></div><p class="menu-kicker">DIGITAL PRACTICE / INDEX</p><nav aria-label="Mobile">${[...site.navigation,{name:'Start a project',href:startUrl}].map((l,i)=>`<a href="${l.href}"><span>0${i+1}</span>${e(l.name)}${arrow}</a>`).join('')}</nav><div class="menu-bottom"><a href="${whatsappUrl}" target="_blank" rel="noopener noreferrer">WhatsApp ↗</a>${site.socials.map(s=>`<a href="${s.url}" target="_blank" rel="noopener noreferrer">${e(s.name)} ↗</a>`).join('')}</div></dialog><noscript><nav class="nojs-nav" aria-label="Chapter navigation"><a href="/#work">Work</a><a href="/#capabilities">Capabilities</a><a href="/#pricing">Investment</a><a href="${startUrl}">Start a project</a></nav></noscript><div class="cursor-label" aria-hidden="true"></div><div class="page-curtain" aria-hidden="true"><span>KR</span></div>`}

export function footer(){return `<footer class="site-footer"><div class="footer-call"><span>KIRATVEER SINGH RALHAN</span><a href="${startUrl}" data-cursor="START">LET’S MAKE IT<br>WORTH REMEMBERING. ${arrow}</a></div><div class="footer-grid"><p>AI-POWERED DIGITAL PRODUCT DEVELOPER<br>${e(site.location)} / WORKING WORLDWIDE</p><div>${site.socials.map(s=>`<a href="${s.url}" target="_blank" rel="noopener noreferrer">${e(s.name)} ↗</a>`).join('')}<a href="${whatsappUrl}" target="_blank" rel="noopener noreferrer">WHATSAPP ↗</a><a href="mailto:${site.email}">EMAIL ↗</a></div><a href="#top">BACK TO TOP ↑</a></div><div class="footer-monogram" aria-hidden="true">KR</div><div class="footer-bottom"><span>© <span data-year>${new Date().getFullYear()}</span></span><span>DESIGN / DEVELOPMENT / AI / MOTION</span></div></footer>`}

function bookHero(){const featured=projects.filter(p=>p.featured).slice(0,4);return `<section class="book-scene hero-world" id="book-scene" aria-labelledby="hero-title"><div class="book-sticky"><div class="hero-ambient" aria-hidden="true"><span>KR</span><i></i></div><div class="book-stage" aria-hidden="true"></div><div class="hero-copy"><p class="hero-identity">KIRATVEER SINGH RALHAN<br><span>CREATIVE DEVELOPER / AI + DIGITAL PRODUCTS</span></p><h1 id="hero-title"><span>I BUILD</span><span>DIGITAL EXPERIENCES</span><span>WITH CODE, AI <em>&</em> MOTION.</span></h1><p class="hero-support">Product thinking, design and development for ambitious businesses.</p><div class="hero-actions"><a class="signal-button" href="#work" data-cursor="EXPLORE">Explore the worlds <span>↓</span></a><a href="${startUrl}" class="line-link" data-cursor="START">Start a project ${arrow}</a></div></div><div class="hero-meta"><span>${e(site.availability)}</span><span>INDIA / WORKING WORLDWIDE</span><span>SCROLL TO DIRECT ↓</span></div><div class="book-fallback"><div class="fallback-book"><div class="fallback-spine"></div><div class="fallback-cover"><span>KR / DIGITAL PRACTICE</span><strong>KIRATVEER<br>SINGH RALHAN</strong><small>SELECTED WORK / 2026<br>DESIGN × AI × DEVELOPMENT</small></div></div><div class="mobile-portal">${featured.map((p,i)=>`<a href="#project-${p.id}"><span>0${i+1}</span>${image(p.image,p.title)}<b>${e(p.title)}</b></a>`).join('')}</div></div><div class="book-bottom"><span class="book-status">THE OBJECT / SCROLL TO OPEN</span><span>SELECTED WORK / 2026</span><div class="book-progress" aria-hidden="true"></div></div></div></section>`}

const conceptLayer=(title,copy,n)=>`<div class="concept-plane plane-${n}"><span>0${n}</span><b>${title}</b><small>${copy}</small></div>`;
export function projectWorld(p,i=projects.filter(x=>x.featured).findIndex(x=>x.id===p.id)){const img=safeMedia(p.image),gallery=p.gallery?.[0],url=safeUrl(p.url),number=String(i+1).padStart(2,'0');const visual=p.id==='qortra'?`<div class="qortra-system" aria-label="Conceptual QORTRA product system">${conceptLayer('BUSINESS CONTEXT','Knowledge with a place to live.',1)}${conceptLayer('AI ASSISTANCE','Suggestions shaped by the workspace.',2)}${conceptLayer('HUMAN APPROVAL','A person remains in control.',3)}${conceptLayer('CONTROLLED ACTION','Reviewed work moves forward.',4)}<div class="qortra-core">Q<span>PRODUCT SYSTEM</span></div></div>`:`<div class="world-media primary-media">${img?image(img,`${p.title} — ${p.imageNote}`):''}<span>${e(p.imageNote||'')}</span></div>${gallery?`<div class="world-media secondary-media">${image(gallery.src,gallery.alt)}<span>${e(gallery.caption)}</span></div>`:''}`;return `<article class="project-world world-${e(p.id)} theme-${e(p.theme||'qortra')}" id="project-${e(p.id)}" data-project-id="${e(p.id)}"><div class="world-sticky"><div class="world-backdrop" aria-hidden="true"><span>${e(p.title)}</span></div><div class="world-head"><span>WORLD / ${number}</span><span>${e(p.shortCategory||p.category)}</span><span>${e(p.status)}</span></div><div class="world-copy"><p>${e(p.shortCategory||p.category)}</p><h2>${e(p.title)}</h2><strong>${e(p.summary)}</strong><p>${e(p.description)}</p><div class="world-links"><a href="/work/${e(p.slug||p.id)}.html" data-cursor="VIEW">Enter case study ${arrow}</a>${url?`<a href="${e(url)}" target="_blank" rel="noopener noreferrer">Visit project ↗</a>`:''}</div></div><div class="world-stage">${visual}</div><div class="world-folio"><span>${number} / 05</span><i></i><span>SCROLL THROUGH WORLD</span></div></div></article>`}

export function projectArchive(items){return items.map(p=>`<a class="archive-row" ${!p.featured?`id="project-${e(p.id)}"`:''} href="${p.hasCaseStudy===false?(safeUrl(p.url)||startUrl):`/work/${e(p.slug||p.id)}.html`}"><span>${e(p.title)}</span><span>${e(p.category)}</span><span>${e(p.status)}</span>${arrow}</a>`).join('')}

function motion(){return `<section class="film-room" id="motion"><div class="film-sticky">${label('07','MOTION / FILM')}<div class="film-title"><h2>MOTION IS<br>PART OF THE <span>SYSTEM.</span></h2><p>Real product, automotive and travel films. Choose a chapter; sound stays off until you ask.</p></div><div class="film-stage">${motionWorks.map((v,i)=>`<article id="film-panel-${i}" role="tabpanel" aria-labelledby="film-tab-${i}" class="film ${i===0?'is-active':''}" data-film="${i}"><video id="${e(v.id)}" controls playsinline muted preload="none" poster="${e(v.poster)}" aria-label="${e(v.title)}"><source src="${e(v.src)}" type="video/mp4"></video><button class="film-play" type="button" data-video="${e(v.id)}" data-cursor="PLAY" aria-label="Play ${e(v.title)}"><span>PLAY</span></button><div class="film-caption"><span>0${i+1} / ${e(v.category)}</span><b>${e(v.title)}</b></div></article>`).join('')}</div><div class="film-selector" role="tablist" aria-label="Choose a film">${motionWorks.map((v,i)=>`<button id="film-tab-${i}" type="button" role="tab" aria-controls="film-panel-${i}" tabindex="${i===0?0:-1}" aria-selected="${i===0}" data-film-select="${i}"><span>0${i+1}</span>${e(v.title)}</button>`).join('')}</div><button class="film-sound" type="button" aria-pressed="false">SOUND OFF</button></div></section>`}

function practice(){return `<section class="capabilities" id="capabilities"><div class="practice-sticky">${label('08','THE PRACTICE')}<div class="practice-intro"><h2>ONE PRACTICE.<br><span>FOUR FORCES.</span></h2><p>Choose a discipline. The image and atmosphere respond.</p></div><div class="capability-visual" aria-hidden="true">${image(capabilities[0].image,'')}</div><div class="capability-index">${capabilities.map((c,i)=>`<details class="capability" ${i===0?'open':''} data-capability-image="${c.image}" data-capability-index="${i}"><summary><span>0${i+1}</span><h3>${e(c.title)}</h3><b>+</b></summary><div><p>${e(c.description)}</p><ul>${c.items.map(x=>`<li>${e(x)}</li>`).join('')}</ul></div></details>`).join('')}</div></div></section><section class="process-section" id="process">${label('09','HOW THE WORK MOVES')}<div class="process-head"><h2>FROM SIGNAL<br>TO <span>SYSTEM.</span></h2><p>A clear path from first conversation to useful work in the world.</p></div><div class="process-track"><div class="process-line"><i></i></div>${process.map((p,i)=>`<article class="process-step"><span>0${i+1}</span><div><h3>${e(p.title)}</h3><p>${e(p.text)}</p></div><small>${e(p.output)}</small></article>`).join('')}</div></section>`}

function pricing(){return `<section class="pricing-section" id="pricing">${label('10','ENGAGEMENT MODES')}<div class="pricing-head"><h2>CHOOSE THE<br>RIGHT <span>SCALE.</span></h2><div><p>Clear starting points. The final scope follows the actual work.</p><label class="currency-control" for="currency-select"><span>VIEW IN</span><select id="currency-select" disabled>${currencies.map(c=>`<option value="${c.code}">${c.code} — ${e(c.name)}</option>`).join('')}</select></label></div></div><div class="price-orbit"><div class="price-index">${packages.map((p,i)=>`<details class="price-item ${p.featured?'is-featured':''}" ${i===1?'open':''}><summary><span>0${i+1}</span><div><h3>${e(p.name)}</h3>${p.featured?'<small>MOST REQUESTED</small>':''}</div><div class="price-value"><small class="price-prefix">From</small><strong data-price="${p.price}">${formatPrice(p.price,'INR')}</strong>${p.plus?'<b>+</b>':''}</div><i>+</i></summary><div class="price-detail"><p>${e(p.category||p.description)}</p><ul>${p.scope.map(x=>`<li>${e(x)}</li>`).join('')}</ul><a href="${startUrl}?service=${encodeURIComponent(p.name)}" data-cursor="START">Start with this mode ${arrow}</a></div></details>`).join('')}</div><aside class="price-signal"><span>INVESTMENT</span><b data-active-package>02</b><p>Starting points for work built with clarity, craft and technical depth.</p></aside></div><div class="pricing-notes"><p>Starting prices. Final proposals depend on scope, functionality, integrations, content and timeline.</p><p id="currency-note">Base prices are in INR.</p></div><details class="addons"><summary>OPTIONAL SUPPORT / ADD-ONS <span>+</span></summary><div>${addons.map(a=>`<article><b>${e(a.name)}</b><span data-price="${a.price}">${formatPrice(a.price,'INR')}</span>${a.plus?'+':''}<small data-price-period="${a.period||''}">${a.period==='month'?'/month':''}</small></article>`).join('')}</div></details></section>`}

function endChapters(){return `<section class="about-section" id="about"><div class="about-image">${image('/assets/images/portrait-garden-960.webp','Kiratveer Singh Ralhan standing in a garden at night')}</div><div class="about-copy">${label('11','THE PERSON IN THE SYSTEM')}<h2>DESIGN MIND.<br>BUILDER’S <em>INSTINCT.</em></h2><p class="about-lead">I’m Kirat, an independent digital product developer working across design, development, AI and content.</p><p>Building products such as TripMitra and QORTRA keeps me close to the decisions behind useful software: what should it do, what can be simpler, and what must hold up when people use it.</p><a href="${startUrl}" class="line-link" data-cursor="START">Build the next one ${arrow}</a></div></section><section class="final-invite" id="contact"><div class="invite-glow" aria-hidden="true"></div><p>KIRATVEER SINGH RALHAN / DIGITAL PRACTICE</p><h2>A ROUGH IDEA<br>IS ENOUGH<br><span>TO BEGIN.</span></h2><div><a class="signal-button" href="${startUrl}" data-cursor="START">Start a project ${arrow}</a><a class="line-link" href="${whatsappUrl}" target="_blank" rel="noopener noreferrer">WhatsApp ${arrow}</a></div><small data-offer>${e(site.offer)}</small></section>`}

export function home(){const featured=projects.filter(p=>p.featured);return `<div class="entry-sequence" aria-label="Kirat — opening sequence"><div class="entry-name">KIRATVEER SINGH RALHAN</div><div class="entry-words"><span>DESIGN</span><span>CODE</span><span>AI</span><span>MOTION</span></div><strong>KR</strong><button type="button">SKIP</button></div>${header()}<div id="top" aria-hidden="true"></div><main id="main" class="experience-main">${bookHero()}<section class="portal-copy" id="work"><p>THE EDITION / FIVE SELECTED WORLDS</p><h2>Ideas become <span>systems.</span></h2><a class="line-link" href="#project-qortra">ENTER WORLD 01 / QORTRA <span>↓</span></a></section><div id="project-worlds">${featured.map(projectWorld).join('')}</div>${motion()}${practice()}${pricing()}${endChapters()}<section class="archive" id="archive">${label('12','OTHER SELECTED WORK')}<div id="project-archive">${projectArchive(projects)}</div></section></main>${footer()}`}

export function caseStudy(p){const index=projects.findIndex(x=>x.id===p.id),next=projects[(index+1)%projects.length],url=safeUrl(p.url);return `${header()}<main id="main" class="case-main theme-${e(p.theme)}"><section class="case-hero" id="top"><a href="/#project-${e(p.id)}" class="case-back">← Selected worlds</a><div class="case-meta"><span>PROJECT / ${String(index+1).padStart(2,'0')}</span><span>${e(p.category)}</span><span>${e(p.status)}</span></div><h1 data-project-title>${e(p.title)}</h1><p class="case-summary">${e(p.summary)}</p><div class="case-cover">${image(p.image,`${p.title} — ${p.imageNote}`,'',true)}<p>${e(p.imageNote)}</p></div><div class="case-facts"><div><span>ROLE / FOCUS</span><p>${e(p.role||(p.services||[]).join(' / '))}</p></div><div><span>CURRENT STATUS</span><p>${e(p.status)}</p></div>${url?`<a class="signal-button" href="${e(url)}" target="_blank" rel="noopener noreferrer">Visit project ${arrow}</a>`:''}</div></section><section class="case-story"><div class="case-chapter"><span>01 / CONTEXT</span><h2>${e(p.challenge)}</h2></div><div class="case-chapter"><span>02 / THE IDEA</span><div><h2>${e(p.idea)}</h2><p>${e(p.description)}</p></div></div><div class="case-chapter"><span>03 / THE EXPERIENCE</span><p class="case-large-copy">${e(p.experience)}</p></div><div class="case-chapter"><span>04 / THE BUILD</span><div><ul class="engineering-list">${(p.engineering||[]).map(t=>`<li>${e(t)}</li>`).join('')}</ul>${p.stack?.length?`<ul class="tags">${p.stack.map(s=>`<li>${e(s)}</li>`).join('')}</ul>`:''}</div></div>${p.gallery?.length?`<div class="case-gallery">${p.gallery.map(g=>`<figure>${image(g.src,g.alt)}<figcaption>${e(g.caption)}</figcaption></figure>`).join('')}</div>`:''}</section><section class="case-next"><span>NEXT WORLD</span><a href="/work/${e(next.slug)}.html">${e(next.title)} ${arrow}</a><a href="${startUrl}">Start a project ${arrow}</a></section></main>${footer()}`}

export function thanks(){return `${header()}<main id="main" class="legacy-thanks"><p>PROJECT RECEIVED.</p><h1>THE NEXT<br>MOVE STARTS<br>HERE.</h1><a href="/thank-you/">Continue →</a></main>${footer()}`}
